### ISSUE TITLE
Request for Clipbert model

### ISSUE THREAD

**Issue by Tangolin** [csbobby/STAR_Benchmark#2]
Hi! Firstly, thank you for your efforts in producing this dataset and generation tool. Is it possible for you to release the clipbert models mentioned in your paper? I would love to compare it across a few datasets and in my own research as well :)

**Comment by csbobby** [comment]
Sure, we are working on that. Please send a request to our email address: starreasoning@gmail.com. Thank you.

**Comment by Tangolin** [comment]
Ok! Thanks for the help!
